# Generated by Django 5.1.1 on 2024-10-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categary_alter_product_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categary',
        ),
    ]
